"""empty message

Revision ID: 33d63faeebd8
Revises: 682bc30a5280
Create Date: 2022-08-29 17:50:47.455074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33d63faeebd8'
down_revision = '682bc30a5280'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
