"""empty message

Revision ID: 682bc30a5280
Revises: 6b67327ff3dd
Create Date: 2022-08-29 18:44:54.222610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '682bc30a5280'
down_revision = '6b67327ff3dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('favorite', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'favorite')
    # ### end Alembic commands ###
