"""empty message

Revision ID: 6b67327ff3dd
Revises: 
Create Date: 2022-08-25 02:30:30.348179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b67327ff3dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('brand_name', sa.String(), nullable=True))
    op.create_foreign_key(None, 'category', 'brand', ['brand_name'], ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'category', type_='foreignkey')
    op.drop_column('category', 'brand_name')
    # ### end Alembic commands ###
