"""empty message

Revision ID: c043d06b95f5
Revises: a8eebbf3896c
Create Date: 2022-08-31 20:50:57.042028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c043d06b95f5'
down_revision = 'a8eebbf3896c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('products', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'products')
    # ### end Alembic commands ###
